
const swaggerAutogen = require('swagger-autogen');

const outputFile = './swagger_output.json';
const endpointsFiles = ['./app.js'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'ClanWolf DataGateway Backend API',
    excerpt: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  // host: 'localhost:3000',
  host: 'dg.clanwolf.net',
  schemes: 'https',
  basePath: '/',
};

swaggerAutogen(outputFile, endpointsFiles, doc).then((r) => console.log(r));
